version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 2003
    volumes:
      - postgres_volumes:/var/lib/postgresql/data
    restart: always

  spring-boot-api:
    container_name: spring-boot-application
    build: ./docker-compose-homework
    depends_on:
      - postgres
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2003
    restart: always

  keycloak-db:
    image: postgres:latest
    container_name: keycloak_db_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 2003
    volumes:
      - keycloak_db_volumes:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    ports:
      - '8080:8080'
      - '8443:8443'
    command:
      - 'start-dev'
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 2003
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 2003
    restart: always

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 2003
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
volumes:
  postgres_volumes:
  keycloak_db_volumes: